# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfd57ef63f3527b30d1b97884dbe9ab1527fb787050868fcd45eec6f2c88689e9086084df38fb97c334fd8654bcd27d87a0cae0c303911455be71b826698f275

test:
  secret_key_base: 8da49d34358aae270ce4dc07b9b4f1fe09e10904aedaf891bfbb481f764e5dd4c7dc47d729b2e7be0d5d07624ace22d1382986bad0ba49d9f18e65be341702e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
